apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-binding
  namespace: dev-john
subjects:
- kind: ServiceAccount
  name: dev-john
  namespace: dev-john
roleRef:
  kind: Role
  name: dev-role
  apiGroup: rbac.authorization.k8s.io
